all:
  hosts:
    node1:
      ansible_host: 172.16.8.15
      ip: 172.16.8.15
      access_ip: 172.16.8.15
    node2:
      ansible_host: 172.16.8.17
      ip: 172.16.8.17
      access_ip: 172.16.8.17
    node3:
      ansible_host: 172.16.8.19
      ip: 172.16.8.19
      access_ip: 172.16.8.19
    node4:
      ansible_host: 172.16.8.21
      ip: 172.16.8.21
      access_ip: 172.16.8.21
    node5:
      ansible_host: 172.16.8.22
      ip: 172.16.8.22
      access_ip: 172.16.8.22
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
